# Generated by Django 4.2.3 on 2023-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('projects', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('why_job', models.TextField()),
            ],
        ),
    ]
