# Generated by Django 4.2.3 on 2023-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_details',
            name='description',
            field=models.CharField(default=models.CharField(max_length=100, unique=True), max_length=5000),
        ),
    ]
