# Generated by Django 4.2.3 on 2023-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0003_internship_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='jobtitle',
            field=models.CharField(max_length=200),
        ),
    ]
