# Generated by Django 4.2.3 on 2023-07-17 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0004_alter_applicant_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='firname',
        ),
        migrations.AddField(
            model_name='applicant',
            name='college',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='edu',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='exp',
            field=models.TextField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='lan',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='lasname',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='loc',
            field=models.TextField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='mobile',
            field=models.CharField(default=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must contain exactly 10 digits and in the range (0-9).', regex='^[0-9]{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='train',
            field=models.TextField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='projects',
            field=models.TextField(max_length=500),
        ),
    ]
