# Generated by Django 4.2.3 on 2023-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0005_rename_name_applicant_firname_applicant_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_details',
            name='perks_and_benefits',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship_details',
            name='requirements',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship_details',
            name='responsibilities',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship_details',
            name='skills',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
