# Generated by Django 4.2.3 on 2023-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0007_alter_applicant_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='jobtitle',
            field=models.CharField(max_length=200),
        ),
    ]
