# Generated by Django 4.2.3 on 2023-08-19 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internportal', '0007_alter_applicant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('ds', 'Data Science'), ('es', 'Embedded Systems')], max_length=2)),
                ('query', models.TextField()),
            ],
        ),
    ]
